package com.merge.backend.domain.notification.entity;

public enum NotificationType {
    SCHEDULE_PUBLISHED,
    SUBSTITUTE_REQUEST_RECEIVED,
    SUBSTITUTE_NO_CANDIDATE,
    SUBSTITUTE_ACCEPTED,
    SUBSTITUTE_ALL_REJECTED,
    SUBSTITUTE_EXPIRED,
    SUBSTITUTE_APPROVED,
    SUBSTITUTE_MANAGER_CLOSED
}
